.\" Manpage for jsh
.\" Author: me@klad.me
.TH jsh-jsh 1 "2020-11-10" "0.1" "jsh jsh. object"


.SH NAME
jsh-jsh \- jsh jsh. object


.SH SYNOPSIS
.TP
.I jsh.shell :String
\- filename for
.B jsh
executable
.TP
.I jsh.script :String
\- filename for current script
.TP
.I jsh.args :Array[String]
\- command line arguments
.TP
.I jsh.exceptions(on) :Boolean
\- controls exceptions for shell functions (on or off)

.SH SEE ALSO
jsh-exceptions(1)

.SH AUTHOR
Alexey Presniakov (me@klad.me)
.br
https://github.com/klad-me/jsh

